# Generated by Django 4.0.3 on 2022-06-27 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Neighbourhood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neighbourhood', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.TextField(max_length=500, null=True)),
                ('image', models.ImageField(upload_to='')),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_update', models.DateTimeField(auto_now_add=True)),
                ('upvote', models.IntegerField()),
                ('downvote', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, null=True)),
                ('password', models.CharField(max_length=100, null=True)),
                ('date_create', models.DateTimeField(auto_now_add=True, null=True)),
                ('neighbourhood', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='basic.neighbourhood')),
            ],
        ),
        migrations.CreateModel(
            name='VoteStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upvotestatus', models.BooleanField(default=False)),
                ('downvotestatus', models.BooleanField(default=False)),
                ('postid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.post')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic.userregister')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='basic.userregister'),
        ),
    ]
