# Generated by Django 4.0.5 on 2022-06-27 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0002_alter_post_date_create_alter_post_date_update_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='downvote',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='upvote',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
