# Generated by Django 4.0.5 on 2022-06-27 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0006_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
