# Generated by Django 4.0.3 on 2022-06-30 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0020_rename_password_userregister_password1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userregister',
            old_name='password1',
            new_name='password',
        ),
    ]
