# Generated by Django 4.0.3 on 2022-06-30 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0021_rename_password1_userregister_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregister',
            name='neighbourhood',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
