# Generated by Django 4.0.3 on 2022-07-01 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0027_alter_comment_body_alter_comment_date_create_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='username',
        ),
    ]
