# Generated by Django 4.0.3 on 2022-07-01 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0029_alter_comment_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='username',
            new_name='user',
        ),
    ]
