# Generated by Django 4.0.5 on 2022-07-02 05:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('basic', '0030_rename_username_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='commets',
            field=models.ManyToManyField(blank=True, null=True, related_name='commented', to=settings.AUTH_USER_MODEL),
        ),
    ]
