# Generated by Django 4.0.5 on 2022-07-02 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0032_comment_dislikes_comment_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(blank=True, null=True, verbose_name=''),
        ),
    ]
