# Generated by Django 4.0.5 on 2022-07-02 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0035_alter_comment_body'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date_create']},
        ),
    ]
