# Generated by Django 4.0.5 on 2022-07-04 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0037_comment_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregister',
            name='password',
        ),
    ]
