# Generated by Django 4.0.5 on 2022-07-04 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0038_remove_userregister_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregister',
            name='neighbourhood',
        ),
    ]
