# Generated by Django 4.0.5 on 2022-07-04 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0040_userregister_neighbourhood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregister',
            name='username',
            field=models.CharField(max_length=100, null=True, verbose_name='Username :'),
        ),
    ]
