# Generated by Django 4.0.5 on 2022-07-05 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0041_alter_userregister_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='global_visibility',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='local_visibility',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='userregister',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
