# Generated by Django 4.0.5 on 2022-07-10 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0045_userregister_age_userregister_bio_userregister_dob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregister',
            name='fname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userregister',
            name='lname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
