# Generated by Django 4.0.5 on 2022-07-11 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0048_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='userregister',
            name='propic',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/'),
        ),
    ]
