# Generated by Django 4.0.5 on 2022-07-14 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0052_post_circle'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='circle_visibility',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
