# Generated by Django 4.0.5 on 2022-07-14 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0053_post_circle_visibility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='circle_visibility',
        ),
        migrations.AlterField(
            model_name='post',
            name='circle',
            field=models.ForeignKey(blank=True, default='No_Circle', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='circle', to='basic.circle'),
        ),
    ]
