# Generated by Django 4.0.5 on 2022-07-15 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0057_post_circle_visibility_alter_post_circle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='circle',
            old_name='discription',
            new_name='description',
        ),
    ]
