# Generated by Django 4.0.5 on 2022-07-28 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0064_friend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='friend',
        ),
        migrations.RemoveField(
            model_name='friend',
            name='user',
        ),
        migrations.AddField(
            model_name='friend',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='friend',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='basic.userregister'),
        ),
        migrations.AddField(
            model_name='friend',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='basic.userregister'),
        ),
        migrations.AddField(
            model_name='friend',
            name='status',
            field=models.CharField(blank=True, choices=[('send', 'send'), ('accepted', 'accepted')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='friend',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='userregister',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='friends', to='basic.userregister'),
        ),
    ]
