# Generated by Django 4.0.5 on 2022-07-28 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0065_remove_friend_friend_remove_friend_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='status',
            field=models.CharField(blank=True, choices=[('send', 'send'), ('accepted', 'accepted'), ('decline', 'decline')], default='send', max_length=100, null=True),
        ),
    ]
