# Generated by Django 4.0.5 on 2022-07-28 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0067_alter_friend_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='status',
            field=models.CharField(blank=True, choices=[('none', 'none'), ('send', 'send'), ('accepted', 'accepted'), ('decline', 'decline')], default='none', max_length=100, null=True),
        ),
    ]
