# Generated by Django 4.0.5 on 2022-08-02 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0068_alter_friend_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend_Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='friend_sugg', to='basic.userregister')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_sugg', to='basic.userregister')),
            ],
        ),
    ]
