# Generated by Django 4.0.5 on 2022-08-15 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0069_friend_suggestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circle',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
