# Generated by Django 4.0.5 on 2022-08-17 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0070_alter_circle_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='global_visibility',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='local_visibility',
            field=models.BooleanField(default=True),
        ),
    ]
