# Generated by Django 4.0.5 on 2022-08-19 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0071_alter_post_global_visibility_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregister',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
