# Generated by Django 4.0.5 on 2022-08-19 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0078_alter_userregister_cover_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregister',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
