# Generated by Django 4.0.3 on 2022-07-08 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_activeusers_alter_message_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activeusers',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='activeusers',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
